WIP: 2024
luxeria/luxstat pull request #10
Opened 2024-03-16 14:29 UTC by xermicus

2024-03-17 13:41 UTC, gandro requested changes
Danke viel mal! Tatsächlich etwas trickier als gedacht, habe mich auch noch etwas eingelesen.

Eine Variante zum Genderdoppelpunkt wäre ansonsten die Verwendung von Slashes wie ich sie hier gesehen habe: https://www.gendercampus.ch/public/sggf/statuten_deu.pdf

Beispiel: "Wahl des Vorstandes, der Präsidentin/des Präsidenten sowie der Revisorin/des Revisors"

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +Ehrenmitgliedern und Gönnern. Als Mitglieder:innen können alle
Ich war mich hier auch schon etwas unsicher, habe mich nochmals kurz schlau gemacht, da ich hier auch schon beim letzten Versuch drüber gestolpert bin. Alle Leitfäden die ich gefunden habe, empfehlen tatsächlich alle, "das Mitglied" nicht zu gendern, da es bereits ein Neutrum ist. Der Duden hat eine Seite dazu:

https://www.duden.de/sprachwissen/sprachratgeber/%E2%80%9ELiebe-Mit%C2%ADglieder%C2%ADinnen-und-Mit%C2%ADglieder%E2%80%9C-%E2%80%93-Personen%C2%AD%C2%ADbezeich%C2%ADnungen

Auch:
https://www.genderleicht.de/textlabor/mitgliederin-geht-das/
https://geschlechtsneutral.net/bereits-geschlechtsneutrale-personenworter/

IMO können wir also Änderungen die "Mitglied" betreffen wieder rückgängig machen.

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +Gönner:innen bzw. Sponsor:innen sind alle Personen, Organisationen
"Sponsor:innen" oder "Sponsoren:innen" ginge beides, aber beides sprachlich etwas holprig.

Mögliche Variantion:
```suggestion
Gönner:innen bzw. Sponsoren:innen sind alle Personen, Organisationen 
```

https://www.scribbr.de/gendern/woerterbuch/sponsor-sponsorin/
https://www.genderator.app/wb/sponsor/

Alternativ: Das Wort "Sponsoren" einfach aus den Statuten rauslöschen. Weiter unten im Text wird nur noch von "Gönner:innen" gesprochen was eifacher zu gendern ist (https://www.genderator.app/wb/g%C3%B6nner)

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +Der Vorstand besteht aus mindestens fünf gewählten
Brauchen wir mindestens 5? Der Absatz danach erlaubt dem Vorstand ja, weitere Rollen frei zu verteilen und hindert und nicht daran, 5 Mitglieder zu halten.

IMO sollten wir das Minimum bei 4 lassen

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +Rechnungsrevisor:in
```suggestion
\item Wahl des Präsident:in, des Vorstand sowie des:der
Rechnungsrevisors:in
```

Wobei ich den Vorstand zuerst erwähnen würde:
```suggestion
\item Wahl des Vorstandes, des:der Präsidenten:in sowie des:der Rechnungsrevisor:in
```

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
>  Rechnungsrevisoren
```suggestion
\item Entlastung des Vorstandes, des:der Kassiers:in und der 
Rechnungsrevisor:innen
```

(oder wieder Variante mit "der Kassierin/des Kassiers und der Rechnungsrevisorinnen/der Rechnungsrevisoren"

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +\item Infrastrukturverantwortlicher:in
```suggestion
\item Infrastrukturverantwortliche:r
```

Allerdings wäre ich eh dafür, die/den Infrastrukturverantwortliche/n nicht in die Statuten aufzunehmnen (siehe oben), da rechtlich nicht relevant.

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
> +Kassier:in mit Einzelunterschrift.
```suggestion
der:die Kassier:in mit Einzelunterschrift.
```

2024-03-17 13:41 UTC, gandro commented on luxstat.tex
>  oder des Vorstandes
Alternativ (Präsident:in IMO unnötig hier):
```suggestion
\item Kenntnisnahme des Jahresberichtes des Vorstandes
```

Alternativ:
```suggestion
\item Kenntnisnahme des Jahresberichtes des:der Präsidenten:in oder des Vorstandes
```

2024-03-17 14:17 UTC, ammoniak commented on luxstat.tex
> +Der Vorstand besteht aus mindestens fünf gewählten
Ich schliesse mich da grandro an

2024-03-23 11:53 UTC, xermicus commented
Danke @gandro fürs Review, stimme allem zu

2024-03-23 12:08 UTC, ammoniak approved these changes
Gsehd guet us

2024-03-23 13:11 UTC, gandro requested changes
Super danke. Hat noch ein paar "Mitglieder:innen" die entfernt werden sollten

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +Passivmitglieder:innen sind natürliche oder juristische Personen,
```suggestion
Passivmitglieder sind natürliche oder juristische Personen, 
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +Ehrenmitglieder:innen sind Personen, welche sich durch
```suggestion
Ehrenmitglieder sind Personen, welche sich durch
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +Passivmitglieder:innen werden zu der Generalversammlung
```suggestion
Passivmitglieder werden zu der Generalversammlung 
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +der Rechnungsrevisor:innen
```suggestion
der Rechnungsrevisoren:innen
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +besetzen. Die Vorstandsmitglieder:innen sind ehrenamtlich tätig
```suggestion
besetzen. Die Vorstandsmitglieder sind ehrenamtlich tätig
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +Vorstandsmitglieder:innen können im Laufe des geltenden
```suggestion
Vorstandsmitglieder können im Laufe des geltenden 
```

2024-03-23 13:11 UTC, gandro commented on luxstat.tex
> +für die Aktiv- und Passivmitglieder:innen fest.
```suggestion
für die Aktiv- und Passivmitglieder fest.
```

2024-03-25 09:42 UTC, gandro commented on luxstat.tex
> +des:der Rechnungsrevisor:in
```suggestion
des:der Rechnungsrevisors:in
```

2024-03-25 09:42 UTC, gandro commented on luxstat.tex
> +persönliche oder finanzielle Leistungen für den Verein besonders
nit: Die Änderungen an diesen beiden Zeilen sind nur noch whitespace

2024-03-25 12:52 UTC, gandro approved these changes

2024-03-27 17:16 UTC, xermicus commented on luxstat.tex
> +persönliche oder finanzielle Leistungen für den Verein besonders
ack

2024-03-27 20:40 UTC, merged

2024-03-27 20:41 UTC, gandro commented
GV hat Änderung bewilligt, merging